Add MAINTAINERS.md and standard repo files
hyperledger/firefly-tezosconnect pull request #2
Opened 2023-09-14 20:54 UTC by nguyer

2023-09-14 21:27 UTC, jimthematrix approved these changes

2023-09-15 16:10 UTC, denisandreenko requested changes

2023-09-15 16:10 UTC, denisandreenko commented on MAINTAINERS.md
> +| Dzianis Andreyenka | awrichar | dzianis.andreyenka@instinctools.com |        |
LFID - Darus

2023-09-15 16:43 UTC, denisandreenko approved these changes

2023-09-15 16:43 UTC, merged